### ISSUE TITLE
numpy 1.24.0 promotion rule change with float32

### ISSUE THREAD

**Issue by lesteve** [colesbury/nogil#102]
In numpy 1.24.0 `np._get_promotion_state()` somehow changes after doing what seems innocent computations. I have no idea how this is possible but here is a snippet that reproduces (not 100% of the time so maybe there is a multi-threading aspect involved).

For more context, see the [Numpy NEP 50](https://numpy.org/neps/nep-0050-scalar-promotion.html). According to the note in this [section](https://numpy.org/neps/nep-0050-scalar-promotion.html#abstract), it seems like this has been added in numpy 1.24, see  but that in principle it is set to 'legacy' and should not change anything compared to numpy < 1.24 behaviour.

```py
# /tmp/test.py
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
from sklearn.utils._testing import assert_array_almost_equal

X_large, y_large = datasets.make_classification(
    n_samples=50,
    n_features=10,
    n_informative=3,
    n_redundant=0,
    n_repeated=0,
    shuffle=False,
    random_state=0,
)

assert np._get_promotion_state() == "legacy"

# Using np.float32 is important to make the issue happen
dtype = np.float32
# Somehow using X_large and y_large directly in the fit does not create the issue
X = X_large.astype(dtype, copy=False)
y = y_large.astype(dtype, copy=False)

est = RandomForestClassifier(n_estimators=10, random_state=0)
est.fit(X_large, y_large)
importances = est.feature_importances_

# Somehow this line is important to make the issue happen
est.set_params(n_jobs=2)
importances_parallel = est.feature_importances_
assert_array_almost_equal(importances, importances_parallel)
assert np._get_promotion_state() == "legacy", f"{np._get_promotion_state()=}"
```

Running the script in a loop like this:
```
(for i in $(seq 10); do python /tmp/test.py 2>&1; done) | grep AssertionError | wc -l
```

I get roughly an assertion 7-8 times ouf of 10. The assertion happens at the end of the script.

I suspect this is possible to reproduce without scikit-learn but the snippet in its current state seems good enough to debug further.

For completeness, here is the list of version I am using:
```
❯ pip list | grep -P 'numpy|scikit-learn'                                       
numpy              1.24.0
scikit-learn       1.1.1
```

Context: in scikit-learn we tried upgrading to numpy 1.24.0 and we bumped into this issue that was making some of our tests failed. See https://github.com/scikit-learn/scikit-learn/pull/25437 for more details.

Maybe this is more an issue for numpy but I thought I would start here first ...

**Comment by colesbury** [comment]
I think what's happening is that there's [some internal code](https://github.com/numpy/numpy/blob/v1.24.0/numpy/core/src/umath/dispatching.c#L955-L959) in NumPy that temporarily switches the promotion behavior to NPY_USE_WEAK_PROMOTION and then switches it back. When running with multiple threads this causes two bugs:

1. Some unrelated code running concurrently in a different thread may be forced to use weak promotion
2. The restoration of the previous promotion behavior gets messed up because of the interleaved execution, which can lead to leaving the promotion state as NPY_USE_WEAK_PROMOTION

I think these problems can occur even upstream with the GIL, but probably are much more rare. It looks like [`promote_and_get_info_and_ufuncimpl`](https://github.com/numpy/numpy/blob/v1.24.0/numpy/core/src/umath/dispatching.c#L957) can release the GIL (in some code paths it allocates a tuple, which can trigger a GC, which can release the GIL). It might be tricky to get a reliable reproducer though.

I think the fix has to involve not modifying the global `npy_promotion_state` and instead passing in the override as a parameter to `promote_and_get_info_and_ufuncimpl`. It might be a bit tricky to thread all the way through.

EDIT: there is a similar switch to NPY_USE_WEAK_PROMOTION in: [`ufunc_object.c`](https://github.com/numpy/numpy/blob/v1.24.0/numpy/core/src/umath/ufunc_object.c#L6409-L6410).

**Comment by ogrisel** [comment]
Thanks @lesteve for the investigation. Just to make sure, you cannot reproduce the problem when using numpy 1.24.0 with the regular CPython (with gil), right?

In your code snippet, I do not understand the motivation for `copy=False` on those lines:

```python
X = X_large.astype(dtype, copy=False)
y = y_large.astype(dtype, copy=False)
```

Since `X_large.dtype` is `float64`, the copy will happen necessarily, right?

Note to @colesbury to explain:

```python
est.set_params(n_jobs=2)
importances_parallel = est.feature_importances_
```

`est.feature_importances_` is a python property that actually uses Python threads to make some computation using numpy when accessing the attribute if `n_jobs > 1`.

Edit: @colesbury is too fast :)

**Comment by colesbury** [comment]
I have a workaround in the NumPy nogil fork: https://github.com/colesbury/numpy/commit/2b12dccacddd05f91390907d0cf1e582d54d88d5

I'm working on re-building the NumPy 1.24.0 wheels.

**Comment by colesbury** [comment]
I've re-uploaded the NumPy 1.24.0 wheels. Please let me know if that fixes the issue for you.

**Comment by lesteve** [comment]
That does seem to fix the issue, thanks a lot!

For completeness I have run my snippet above 100 times without seeing the issue appear.
