### ISSUE TITLE
Is GC still working?

### ISSUE THREAD

**Issue by davidhalter** [colesbury/nogil#12]
Sorry if this is just noise. However, I was reading quite a bit of your code. It looks like a very interesting approach to this problem.

However I do not seem to find the place where the `_PyGCHead_SET_NEXT` and `_PyGCHead_SET_PREV` macros are called or where `_gc_prev` and `_gc_next` are set in your code. This might lead to GC not working at all, which means probably better benchmarks, but memory leaks.

Is this something I'm misunderstanding? Maybe your patches towards `Modules/gcmodule.c` somehow still track those objects. However, I do not understand where that would happen, since the content of `_PyObject_GC_TRACK` seems to have moved nowhere specific.

Please let me know what you think!

**Comment by colesbury** [comment]
Thanks for looking over the code. The garbage collector still works (and `test_gc.py` still passes).

The linked list (`_gc_prev` and `_gc_next`) is only maintained during garbage collection. It's created in `update_ref`:

https://github.com/colesbury/nogil/blob/703a299d9f412b38caf3d2301d1a365135b66bff/Modules/gcmodule.c#L840-L843

This works by traversing the `mimalloc` heap to find all objects:

https://github.com/colesbury/nogil/blob/703a299d9f412b38caf3d2301d1a365135b66bff/Modules/gcmodule.c#L452-L485

`_PyObject_GC_TRACK` is in `pycore_gc.h`. (This is probably harder to find because GitHub disables code search in forked repos.) It works by simply setting the least-significant-bit in the first word of the object header to 1. (Untrack sets it to 0). 

https://github.com/colesbury/nogil/blob/703a299d9f412b38caf3d2301d1a365135b66bff/Include/internal/pycore_gc.h#L110-L121

If you jump back to `gcmodule.c`, you'll see that `visit_page` (called by `visit_heap`) checks for tracked objects. There's a tiny bit of trickiness in `visit_page` because in the debug build, the embedded mimalloc inserts two words before the object header.

**Comment by davidhalter** [comment]
Thanks a lot for explaining!

I guess the missing piece for me was really this one (from your [design document](https://docs.google.com/document/d/18CXhDb1ygxg-YXNBJNzfzZsDFosB5e6BfnXLlejd9l0/edit#)):

> Additionally, mimalloc’s layout of objects in the heap allows for finding all GC-tracked objects without maintaining an explicit list, which isn’t possible to do efficiently with pymalloc or other allocators built on top of malloc.

I wasn't aware that any allocator could do this efficiently :) Interesting!

----------

An additional question from reading your design document:

> With additional changes, the linked-list could probably be entirely removed to improve performance.

(I assume you mean the `PyGC_Head` linked list and I have no knowledge about mimalloc heaps).

It's also interesting to get rid of the linked list, because that would probably free up quite a bit of memory. How would you still maintain the generational GC? Just additional data next to the `GC_BITS_IS_TRACKED` flag?
