### ISSUE TITLE
ubuntu 20.04 cannot install numba 0.54

### ISSUE THREAD

**Issue by hkhk366** [colesbury/nogil#31]
Hello,
I would like to report an issue.
I downloaded numba from here: https://d1yxz45j0ypngg.cloudfront.net/numba/
I run "pip install numba-0.54.0-nogil39-nogil_39_x86_64_linux_gnu-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
It gives me the following error
"ERROR: numba-0.54.0-nogil39-nogil_39_x86_64_linux_gnu-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform."

Would you mind to double check this whl? Thank you.

**Comment by colesbury** [comment]
Numba doesn't work with nogil Python because the bytecode format has changed. The package you linked to is from an earlier attempt to build Numba before I realized the dependency on bytecode. I'll delete the package to avoid confusion.

I'm tracking which C API extensions work in the wiki:
https://github.com/colesbury/nogil/wiki/Supported-C-API-Extensions

**Comment by hkhk366** [comment]
Thank you for telling me that numba has problems, and I hope this project can go further and further. I do not have further questions, I will close this ticket, thanks.
