### ISSUE TITLE
Assorted observations

### ISSUE THREAD

**Issue by o11c** [colesbury/nogil#4]
Disclaimer: I would not, by any means, call myself an expert at either concurrency or CPython. Nonetheless, several things jumped out at me (a couple of which are quite concerning; others of which are quibbles, guesses, or random ideas)

This is a mixture of feedback on the design document (mostly in order) and the implementation (randomly).

I've done this as a single post with checkboxes, since I feel that's best at least for first glance. Feel free to split parts off into separate issues, or edit it if checkboxes aren't enough.

***

- [ ]  

> Replacing Py_INCREF and Py_DECREF with atomic variants would result in a 60% average slowdown on the pyperformance benchmark suite.

Really? What exactly are you comparing here? It can't be "just use atomic operations; keep the GIL for now", since that would have <2% performance impact (since the GIL makes you uncontended) even if literally every instruction was a refcount change. And it can't be "use atomic operations and ignore the GIL" because of all the C method implementations that must be made atomic.

***

- [ ]  

To avoid the possibility of false sharing between unrelated objects (is it worth it?), you must guarantee either:

* all (non-immortal) object allocations are rounded up to a minimum of 64 bytes (or whatever the cacheline size is)
    * remember that you're increasing the default object size already in your patch.
    * note that `dict` already exceeds this on vanilla CPython (at least on 64-bit platforms), and dict outnumbers ordinary objects (since they all have a dict). The biggest loser is probably `int`
* the allocator only ever hands out a given cacheline to the same thread
    * some allocators do this semi-accidentally as part of improving their own multithreaded performance; this may or may not apply if the memory is later freed then reused.

Do you have to worry about false sharing between the local and shared refcounts that are right next to each other? Thinking particularly about the case of exactly 2 threads, which wouldn't be contending if the local count was stored indirectly.

***

- [ ]  

What fraction of refcount calls are to immortal objects (also, talk about `gc.freeze`)? Even though *most* objects aren't immortal, the immortal objects are by far the most common... It's unfortunate that we have to choose between "optimize for branch prediction" and "optimize for memory accesses" ... since your code is more than a simple branch, we might also have to care about how *multiple* branches are predicted.

***

- [ ]  

Use of `uint32_t` for refcounts is scary, especially when you're stealing 2 bits from it. Making an 8GB `list` (or multiple smaller ones) is quite doable (about 5 seconds) on current systems: `[object()] * 2**30` (warning: double-check your free RAM before testing that).

***

- [ ]  

Is it really necessary to do a full-blown CAS, rather than an `acq_rel` sub?

***

- [ ]  

Use of non-`_explicit` atomic operations is almost always a bug. Particularly, that means you're using `seq_cst` semantics for (shared) incref even though it only needs `relaxed` (since you already own a reference, you don't have to worry about the last reference disappearing. I admit to not knowing how biased locking affects this)!

***

- [ ]  

Casting to atomic is UB, and since the variables are newly-introduced here, it should be avoidable by using the correct type in the first place.

***

- [ ]  

Wouldn't this be a great opportunity to say "we no longer support compilers that haven't been updated since 2011" and just write it in C11 without all the wrappers? Or at least just use a drop-in implementation of `<stdatomic.h>`?

***

- [ ]  

If putting a deferred object on the stack doesn't increase the refcount, what happens you then call back into Python code that nukes the reference and then invokes the GC? (If this is impossible, *prove it*, since you've eliminated the usual (universal) guarantee)

***

- [ ]  

If you force a single allocator (which is not a bad idea, really), you should address what happens to *lower*-level allocator replacements like `AddressSanitizer` uses ... I *think* the fact that it calls `mmap` should suffice, but this should be explicitly tested and documented.

***

- [ ]  

> This design is implemented for the list and dict classes

Why, oh why, must `set` always be a second-class citizen?

***

- [ ]  

> re-used for other Python objects of the same size

really "same size **class" or maybe "same size, as rounded up for allocation purposes" since you haven't introduced that term yet. Really, all that matters is that the start of the object never becomes the middle of a different object.

***

- [ ]  

> C11 acquire-release semantics (or stronger) to ensure proper ordering. This is “free” on x86-64: these accesses are compiled to plain load and store instructions

It's worth noting that this only applies to simple loads and stores, not to things like add (let alone CAS). And it's hard to implement a concurrent algorithm using only atomic stores. I would phrase it something like "loads are free; stores are free but require taking the (much more expensive) lock anyway"

***

- [ ]  

> stores a Python object pointer tagged with least-significant-bit set

There's another alternate approach: there are two "arrays" - one of ordinary objects, and a separate dynamic_bitset - then use the same index to access the related items from each. This uses 1/64 more memory but avoids the masking.

(this is very similar to the rule "prefer struct of arrays, not array of structs")

***

- [ ]  

I'm rather skeptical of all the asm this adds (especially that `return 0;` fallback; yikes! Better to `#error` than leave that kind of landmine).

With a modern compiler you can almost always coerce it into generating optimal code without it, so *any* asm block should have a justification of not just why it is correct, but why you haven't been able to do it properly.

**Comment by colesbury** [comment]
Thanks for your comments and taking the time to read through the design and code.

> Really? What exactly are you comparing here? It can't be "just use atomic operations; keep the GIL for now"

It's just "[use atomic operations; keep the GIL](https://github.com/colesbury/nogil/commits/always_atomic)". Atomic instructions (Intel calls them "Locked Atomic Operations") are much [more expensive](https://uops.info/table.html?search=INC%20(M64)&cb_lat=on&cb_tp=on&cb_uops=on&cb_ports=on&cb_SKL=on&cb_measurements=on&cb_doc=on&cb_base=on) than their non-atomic counterparts. For example, recent Intel and CPUs can execute one `inc` instruction every cycle, but one `lock inc` every ~18 cycles. Things might be getting better. Performance of atomics is reportedly improved on AMD's [Zen 3](https://www.anandtech.com/show/16214/amd-zen-3-ryzen-deep-dive-review-5950x-5900x-5800x-and-5700x-tested/6#:~:text=LOCK%20(ALU),7%20cycle%20latency) architecture and also on Apple's M1 CPU.

>  To avoid the possibility of false sharing between unrelated objects (is it worth it?)...

It's not worth addressing it. Consider that the same potential issue exists many other languages (Swift, Go, Java, even C and C++). They do not address potential false sharing by making allocations larger in general. For what it's worth, I've only encountered false sharing once so far in this project and it was between different fields of the same internal C data structure. 

Contention on reference count fields is a real concern, but that's more like true sharing of the same data.

> Do you have to worry about false sharing between the local and shared refcounts that are right next to each other?  Thinking particularly about the case of exactly 2 threads...

I don't think it's worth trying to optimize for this case. Most objects are either accessed by a single thread or by many threads. Although biased reference counting uses two refcount fields, it is only optimized for access by a single thread. Frequent access by two or more threads is addressed by immortalization and deferred reference counting. They are not panaceas though, and contention on reference count fields can still be an obstacle of scaling. This is true of other languages that uses reference counting pervasively, like Swift.

> What fraction of refcount calls are to immortal objects (also, talk about gc.freeze)? Even though most objects aren't immortal, the immortal objects are by far the most common... 

About 60% of calls to DECREF are are avoided, either because the object is immortal, the reference is deferred, or the variable is a [non-reference counted alias](https://github.com/colesbury/nogil/blob/84c1b14af40d406a789d4229f67546b069cc4a25/Python/ceval2.c#L1478-L1485) in the interpreter.


> It's unfortunate that we have to choose between "optimize for branch prediction" and "optimize for memory accesses"

Immortalization and biased reference counting add one branch each. The branches are not free (see the performance section of the design), but they are very cheap. I don't understand the framing as a choice between "optimize for branch prediction" and "optimize for memory accesses". What memory access optimizations are you referring to? And which branch prediction optimizations?

Modern branch predictors are excellent. See for example, ["Branch Prediction and the Performance of Interpreters - Don’t Trust Folklore"](https://hal.inria.fr/hal-01100647/document). (The last author of that paper also designed the TAGE predictor, which is rumored to be what Intel uses.) On my machine (Broadwell CPU), the overall branch misprediction rate for running a selection of the Python test suite is <2%. Consider also that the branch misprediction penalty is much smaller than it used to be (about 15-20 cycles).

> Use of uint32_t for refcounts is scary...

Yes, this needs to be changed, but it's a low priority. There are a number of design choices here, and I'm not sure which is best. 

> Is it really necessary to do a full-blown CAS, rather than an acq_rel sub?

On x86 and ARM read-modify-write operations (like CAS) compile to the exact same code for both seq_cst and acq_rel. There is a difference with the Power ISA, but I'm not optimizing for that currently. Preferring seq_cst when it doesn't affect performance simplifies the code. Eventually, I'd like to optimize for Power, but that's a ways away and will require access to a Power machine.

> Use of non-_explicit atomic operations is almost always a bug. Particularly, that means you're using seq_cst semantics...

The desire is to use seq_cst semantics (for the reasons I wrote above).

> Casting to atomic is UB, and since the variables are newly-introduced here, it should be avoidable by using the correct type in the first place.

The cure is worse than the disease here. Casting to atomics is pretty low risk here -- we are performing atomic operations on primitive data types with natural alignment. We care about compatibility with C++. Using atomic variables in object.h would change the object to non-copyable and non-movable in C++. You would substitute one category of undefined behavior (casting to atomic type) for another (undefined behavior with respect to initialization).

It might be worth eventually using GCC's [atomic builtins](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html) when available (also available on Clang) which operate on non-atomic types. For now, I think that would just add more code (and more code = more possibility for real bugs).

> Wouldn't this be a great opportunity to say "we no longer support compilers that haven't been updated since 2011" 

No.  Windows support (MSVC) is important. Last I read, C11 atomics is [on the roadmap](https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/), but not implemented  (it's an "optional" feature in C11).

> If putting a deferred object on the stack doesn't increase the refcount, what happens you then call back into Python code that nukes the reference and then invokes the GC?

The GC adds back all the missing deferred reference counts before actually performing garbage collection. That's why deferring reference counts is limited to the interpreter -- the GC needs to be able to locate all deferred references.

> If you force a single allocator (which is not a bad idea, really), you should address what happens to lower-level allocator replacements like AddressSanitizer...

The included `mimalloc` replaces Python's `obmalloc`. PyMem_RawMalloc/Free still uses malloc/free. It's possible to switch those to use mimalloc as well, but I don't see a compelling reason for either choice.

AddressSanitizer behaves similarly as it did with `obmalloc`. It'll catch issues with malloc/free and stack corruption but not with most objects allocated via obmalloc or mimalloc, since they use arenas. But those issues are well handled by the debug allocator (`--with-pydebug`), so it's not much of a concern.

> really "same size **class"...

Yes

> It's worth noting that this only applies to simple loads and stores, not to things like add (let alone CAS)....

Yes. The footnote is only referring to accesses to the version counter. These accesses only uses loads and stores and not things like CAS.

> There's another alternate approach: there are two "arrays" - one of ordinary objects, and a separate dynamic_bitset...

I considered this approach when writing the interpreter, but I couldn't figure out a way to make it efficient. In particular, setting and clearing bits in a bitmask is more expensive than the single `and` instructions used to clear the mask. Modifying the bitmask needs to happen every time the interpreter writes to a virtual register. These writes to virtual registers happen in similar proportion to reads.

> ... (especially that return 0; fallback; yikes! Better to #error than leave that kind of landmine).

Yes. I ran into this earlier this week. Better to use `#error`.

> With a modern compiler you can almost always coerce it into generating optimal code without it...

This has not been my experience.

**Comment by o11c** [comment]
>> Really? What exactly are you comparing here? It can't be "just use atomic operations; keep the GIL for now"

> It's just "use atomic operations; keep the GIL". Atomic instructions (Intel calls them "Locked Atomic Operations") are much more expensive than their non-atomic counterparts. For example, recent Intel and CPUs can execute one inc instruction every cycle, but one lock inc every ~18 cycles. Things might be getting better. Performance of atomics is reportedly improved on AMD's Zen 3 architecture and also on Apple's M1 CPU.

Well, this is embarassing. It turns out my "test performance of atomics vs non-atomics" benchmark was flawed: it actually used atomics unconditionally (but with minor differences so there was a tiny performance difference). Since it performed "well enough" on my workloads that I never noticed.

Anyway, I now have some actual numbers. With atomics:

* my own "literally nothing but incref/decref" (not cpython) loop benchmark is about 60% slower
* pyperformance's sum of individual tests is about 40% slower
* pyperformance in total is about 20% slower (using `time pyperformance run` - not sure what all gets done in the harness there, but it was still the just-built cpython - it's definitely *not* the `pip` part though, since that is very short)

This is on an AMD Ryzen 5 2600 Six-Core Processor, so Zen+ (significantly older than Zen 3).

(incidentally, it is *really* irritating that it doesn't save results unless you explicitly ask you to)

>> What fraction of refcount calls are to immortal objects (also, talk about gc.freeze)? Even though most objects aren't immortal, the immortal objects are by far the most common...

> About 60% of calls to DECREF are are avoided, either because the object is immortal, the reference is deferred, or the variable is a non-reference counted alias in the interpreter.

Hm, I was thinking in terms of whether those `unlikely` branches were actually correctly annotated. Also remember that there's `__builtin_expect_with_probability` now.

> Immortalization and biased reference counting add one branch each.

There's a lot more than a single branch in the biased reference counting logic; most involve "merge" and "queue".

I'll freely admit that I don't understand the algorithm, but ... are you sure you can't just use the standard "strong/weak" logic used by most smart pointers? Here "weak" would mean "shared" - the one actually in charge of the allocation, and "strong" would mean "local". If there are any "strong" refs at all, they collectively own a single "weak". Unlike most, resurrection is meaningful, but (assuming this paradigm is applicable in the first place) that's a trivial extension to implement (if it's even desirable).

> I don't understand the framing as a choice between "optimize for branch prediction" and "optimize for memory accesses". What memory access optimizations are you referring to? And which branch prediction optimizations?

Considering just immortalization: if it didn't exist, that's one less branch, but requires doing a lot more writes (and thus dirty cache lines).

This was just bemoaning the state of the universe, though.

>> Is it really necessary to do a full-blown CAS, rather than an acq_rel sub?

> On x86 and ARM read-modify-write operations (like CAS) compile to the exact same code for both seq_cst and acq_rel. There is a difference with the Power ISA, but I'm not optimizing for that currently. Preferring seq_cst when it doesn't affect performance simplifies the code. Eventually, I'd like to optimize for Power, but that's a ways away and will require access to a Power machine.

You missed my point there. Your decref has a *loop* where most algorithms only need a single `fetch_sub`.

>> Use of non-_explicit atomic operations is almost always a bug. Particularly, that means you're using seq_cst semantics...

> The desire is to use seq_cst semantics (for the reasons I wrote above).

That doesn't explain why you think you actually *want* `seq_cst`, only an observation that it doesn't matter on some arches. I've never come across a real use case for it in the first place - remember, it only matters when you have *multiple* atomic variables that otherwise wouldn't be sequenced!

 > Using atomic variables in object.h would change the object to non-copyable and non-movable in C++. You would substitute one category of undefined behavior (casting to atomic type) for another (undefined behavior with respect to initialization).

Er, what? "noncopyable" makes a compile-time error ... and I'm not sure it's even meaningful to do that, since you'll end up with a bogus reference count already, and `PyObject_HEAD_INIT` is an initializer, not an expression.

You could always do `struct copyable_atomic : std::atomic` and implement copy ctor/assign in terms of relaxed load and store.

> It might be worth eventually using GCC's atomic builtins when available (also available on Clang) which operate on non-atomic types. For now, I think that would just add more code (and more code = more possibility for real bugs).

As long as you don't write the code by hand, it should be fine. Just stick a couple tables in a .py file and use their cross product to generate all the wrappers automatically.

> No. Windows support (MSVC) is important. Last I read, C11 atomics is on the roadmap, but not implemented (it's an "optional" feature in C11).

Even if you need the MSVC ABI, there's always Clang, which an increasing number of organizations/projects seem to be using exclusively.

Remember that time Youtube randomly decided to execute Internet Explorer 6? Sometimes the only way to force the world to move forward is to break things. It's not like "I have to upgrade to python-latest this exact moment" is a thing.

(but again: third-party implementations of `<stdatomic.h>` for MSVC exist, so why not mandate one?)

>> With a modern compiler you can almost always coerce it into generating optimal code without it...

> This has not been my experience.

Are you telling me you can't get the compiler to generate a `cmp`?

The only place where there might be *any* reason to use assembly is `_Py_ThreadId`, and even there I'm not convinced. Considering several possibilities:

Approach | Valid per | Cost
---|---|---
gettid | OS | Obvious, but paying for a full syscall makes it clearly unsuitable (caching PIDs has proven to never be a good idea).
pthread_self | all Unixen | pay for a single function call, but the body of that function is as simple as it gets. Theoretically this might fail if `pthread_t` is a struct, but I don't know any such OS (and if there is one, chances are it won't compile the other stuff we already require)
just ask `mimalloc`? | universal | Will presumably be updated. For use in CPython itself this would be fine, but for anybody including Python.h they'd have to pay for a function call (since mimalloc should not be part of the public API)
&errno | universal | Function call + 2 memory reads. (glibc maintainers didn't seem excited about hard-coding the slot); very hot.
&some_thread_local | universal | 1 memory read in the "local-exec" model; 2 memory reads if you're in the "initial-exec" model (which, despite the name, does not actually prevent `dlopen`). Expensive in the dynamic models, which call a function that might have to allocate memory (assuming the relocation can't handle it. Hm, I need to test why it doesn't always appear to do so, even when initial-exec dlopen works. Is it related to not having threads yet? Am I misunderstanding what the "make performance good" relocation does?)
value of FS/GS itself | OS + architecture | special instruction (GCC has an intrinsic for it, at least) that may fail on old hardware (probably not relevant), fallback to syscall; this is more expensive to access than reading through the segment registers, thus the whole gnu2 dialect thing. But actually ... given the usual double-lookup, is it actually guaranteed that FS will never change?
value read at some offset within FS/GS | exact libc | single memory read; how sure are you that libc is not going to change? Remember that you can use different LIBCs (e.g. musl, which does at least some things differently) on the same machine! (also note: this does not actually require assembly; you can use `__seg_fs`)

I expect that, by far, the most important thing is to apply `__attribute__((const))`, since most functions (but especially the interpreter loop itself) will do multiple increfs/decrefs and they shouldn't have to fetch it multiple times. (the fact that this attribute is already applied to `pthread_self` and `__errno_location` means that the requirement of "must not ever change" clearly applies only for accesses within a thread). *This* is the kind of thing that aggressive use of assembly inhibits.

You probably want to make `_Py_DecRefShared` and such take the thread ID as an argument so that callers that can only see the header can still merge the calls.

Given this, I don't think a single function call is significant overhead, so all of the universal techniques are roughly equal.
