### ISSUE TITLE
Cannot install SciKit-learn with Mac OS

### ISSUE THREAD

**Issue by Cheukting** [colesbury/nogil#73]
## Environment
Python: nogil-3.9.10 on pyenv
OS: mac OS 12.4

When doing `pip install scikit-learn` as usual on a fresh virtualenv (nothing else installed). It looks like it cannot find the right version of numpy. (sorry the error message is too long can I don't know what is important to post here) It just keep trying different versions of scikit-learn but all of them failed eventually.

**Comment by colesbury** [comment]
Hi @Cheukting, is this on the new ARM (M1) mac or an x86-64  (Intel) mac? (If you're not sure the command `uname -a` will tell you)

I'll look into providing pre-built packages for NumPy and SciKit-learn on macOS, but the ARM and Intel CPUs need different packages, so it'd be helpful to know which one to prioritize.

**Comment by Cheukting** [comment]
Hi @colesbury thanks for the quick reply. The processor on my mac is 3.1 GHz Dual-Core Intel Core i7 so yes it's an x86-64 (Intel) mac.

Your keynote at EuroPython brings me to this. Thank you for the great work

**Comment by colesbury** [comment]
I've uploaded wheels for NumPy, SciPy, and scikit-learn on x86-64 macOS. You should be able to run `pip install scikit-learn` now. Let me know if you run into any issues.

**Comment by colesbury** [comment]
I also added wheels for arm64 macOS (NumPy, SciPy, scikit-learn) in case people want to use that.

There may be some slight differences from the "official" builds of those projects because of different BLAS and LAPACK libraries. (I built with the homebrew provided OpenBLAS libraries and without OpenMP support). I don't expect this to make much of a difference, but it might show up as a performance difference for some operations.
